from __future__ import annotations

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from linkedin_client import create_text_post, get_member_urn

ROOT = Path(__file__).resolve().parents[1]


def main():
    enabled = os.getenv("AUTO_POST_ENABLED", "false").lower() == "true"
    force_run = os.getenv("FORCE_RUN", "false").lower() == "true"

    if not enabled and not force_run:
        print("AUTO_POST_ENABLED is not true and FORCE_RUN is not true. Skipping LinkedIn publish.")
        return

    token = os.getenv("LINKEDIN_ACCESS_TOKEN", "").strip()
    person_urn = os.getenv("LINKEDIN_PERSON_URN", "").strip()
    version = os.getenv("LINKEDIN_VERSION", "202609").strip() or "202609"

    if not token:
        raise RuntimeError("Missing LINKEDIN_ACCESS_TOKEN GitHub Secret.")

    post_file = ROOT / "output" / "latest.txt"
    if not post_file.exists():
        raise RuntimeError("output/latest.txt does not exist. Run generate_post.py first.")

    # Read the exact UTF-8 content generated by the generator.
    post = post_file.read_text(encoding="utf-8").strip()

    if not post:
        raise RuntimeError("Generated post is empty.")

    # LinkedIn text-post payload uses the complete commentary string.
    # Do not slice/truncate it here.
    print("=" * 70)
    print("LINKEDIN PUBLISH VALIDATION")
    print("=" * 70)
    print(f"Character count : {len(post)}")
    print(f"UTF-8 byte count: {len(post.encode('utf-8'))}")
    print(f"API version     : {version}")
    print(f"Starts with     : {post[:180]!r}")
    print(f"Ends with       : {post[-180:]!r}")
    print("=" * 70)

    # Basic safety checks before sending anything to LinkedIn.
    if len(post) > 3000:
        raise RuntimeError(
            f"Generated post is {len(post)} characters. "
            "Refusing to publish because it exceeds the 3000-character safety limit."
        )

    if "📘 You can get the complete guide from here:" not in post:
        raise RuntimeError("Guide CTA is missing from the generated post.")

    if "http://" not in post and "https://" not in post:
        raise RuntimeError("No URL found in generated post.")

    if not person_urn:
        person_urn = get_member_urn(token)
        print(f"Resolved LinkedIn member URN: {person_urn}")
    elif not person_urn.startswith("urn:li:person:"):
        person_urn = f"urn:li:person:{person_urn}"

    result = create_text_post(token, person_urn, post, version)

    if result.get("status") not in (200, 201):
        raise RuntimeError(
            f"LinkedIn did not return a successful status: {result.get('status')}"
        )

    post_id = result.get("post_id")
    if not post_id:
        raise RuntimeError(
            "LinkedIn returned success but no post ID was found. "
            f"Response body: {result.get('response', '')}"
        )

    meta_file = ROOT / "output" / "metadata.json"
    metadata = (
        json.loads(meta_file.read_text(encoding="utf-8"))
        if meta_file.exists()
        else {}
    )

    metadata.update(
        {
            "published": True,
            "linkedin_post_id": post_id,
            "linkedin_status": result.get("status"),
            "linkedin_api_version": version,
            "published_character_count": len(post),
            "published_utf8_byte_count": len(post.encode("utf-8")),
        }
    )

    meta_file.write_text(
        json.dumps(metadata, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    print("=" * 70)
    print("LinkedIn post published successfully.")
    print(f"Post ID: {post_id}")
    print(f"Characters sent: {len(post)}")
    print("=" * 70)


if __name__ == "__main__":
    main()
